### PR TITLE
std::array serialization cleanup

### LINKED ISSUE #73: revisit efficiency of serialization of tensors of std::complex
see @shiozaki comment: https://github.com/BTAS/BTAS/commit/17ea3375c02d08db7352860f025d387676252a7b#commitcomment-9230781

### PR DESCRIPTION
**Pull request by evaleev**
@shiozaki please check with bagel. This should make arrays of bitwise-serializable types serializable. This will probably need boost 1.56 to work optimally.

1) declared std::array<T> bitwise serializable if T is (always good idea......?)

2) switched tests to binary archives, save few secs to check whether serialization is optimized

this supersedes changes in #40 , closes #73

### CODE REVIEW

**Comment by shiozaki** [comment]
@evaleev  as of 1.57 boost::serialization::make_array returns boost::serialization::array - and I wonder why this works. Could you elaborate?

http://www.boost.org/doc/libs/1_57_0/boost/serialization/array.hpp

**Comment by evaleev** [comment]
that's the proxy class for serializing array for which there is support for
optimized serialization in binary archive. this optimization is only
enabled if type T is bitwise-serializable. This optimization obviously
breaks portability between different-endianness platforms, but OK for the
efficiency sake.

On Sun, Jan 11, 2015 at 6:07 PM, Toru Shiozaki <notifications@github.com>
wrote:

> @evaleev <https://github.com/evaleev> as of 1.57
> boost::serialization::make_array returns boost::serialization::array - and
> I wonder why this works. Could you elaborate?
>
> http://www.boost.org/doc/libs/1_57_0/boost/serialization/array.hpp
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BTAS/BTAS/pull/74#issuecomment-69516637>.
>



-- 
web: valeyev.net

**Comment by shiozaki** [comment]
No, my question is that
(1) varray serializes using
```
  template<class Archive, typename T>
  void save (Archive& ar, const btas::varray<T>& x, const unsigned int version)
  {
      const typename btas::varray<T>::size_type n = x.size();
      ar << n << boost::serialization::make_array(x.data(), n);
  }
````
(2) boost::serialization::make_array returns boost::serialization::array which is not std::array
(3) I do not understand why this pull request changes behavior of this.

**Comment by evaleev** [comment]
boost::serialization::array is the proxy class that was designed for help
with serializing data of varray ilk. std::vector is serialized using this
function (btw its capacity is not serialized
http://www.boost.org/doc/libs/1_57_0/boost/serialization/vector.hpp). I do
not see any advantage to casting to std::array first.

On Mon, Jan 12, 2015 at 8:43 AM, Toru Shiozaki <notifications@github.com>
wrote:

> No, my question is that
> (1) varray serializes using
>
>   template<class Archive, typename T>
>   void save (Archive& ar, const btas::varray<T>& x, const unsigned int version)
>   {
>       const typename btas::varray<T>::size_type n = x.size();
>       ar << n << boost::serialization::make_array(x.data(), n);
>   }
>
> (2) boost::serialization::make_array returns boost::serialization::array
> which is not std::array
> (3) I do not understand why this pull request changes behavior of this.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BTAS/BTAS/pull/74#issuecomment-69571089>.
>



-- 
web: valeyev.net

**Comment by shiozaki** [comment]
No, you haven't got my question. I know all these things.
This commit potentially changes the behavior of serializing a Tensor whose storage is varray with complex double? Do you agree?

**Comment by shiozaki** [comment]
As I wrote in #73
>Looking at boost/serialization/complex.hpp it may be fine by now (but I do not know).

I guess you are implying that complex\<double\>\* now serializes bit-wise no matter what, which then legitimates this commit that reverts btas::make_array which was essentially doing 
```
-  template <typename T>
-  auto make_array(const std::complex<T>* data, const size_t n) -> decltype(boost::serialization::make_array(reinterpret_cast<const T*>(data), 2*n)) {
-    return boost::serialization::make_array(reinterpret_cast<const T*>(data), 2*n);
-  }
```
i.e., casting complex\<double\>\* to double\* of twice as long.

**Comment by evaleev** [comment]
Yes, std::complex<T> will serialize in bitwise fashion if T is also bitwise
serializable. This obviously only matters for some archives. The new
approach eliminates the need to specialize varray serialization for other
types (toru::quaternion). Also for some archives (XML?) flattening out the
data is undesirable since it makes the interpretation less clear. The new
approach will serialize varray of complex to XML nicely.

**Comment by evaleev** [comment]
Yes

**Comment by shiozaki** [comment]
thanks for clarification!

**Comment by evaleev** [comment]
no problem ... sorry for being dimwitted this morning

from looking at vector.hpp I actually need to be a bit more careful ... a small changeset is coming.

**Comment by evaleev** [comment]
yes, XML serialization of varray is broken at the moment. fixes coming

**Comment by evaleev** [comment]
xml works. ready to merge, iff bagel validation passes.

**Comment by shiozaki** [comment]
@evaleev Is the validation running on your side or shall I compile and test manually? I believe this should not break anything in bagel (and bagel's serialization tests are not thorough).

**Comment by evaleev** [comment]
If you could do this would be great.

**Comment by shiozaki** [comment]
```
../../../../src/util/serialization.h:258:10: error: redefinition of 'template<class Archive, class T, long unsigned int N> void boost::serialization::serialize(Archive&, std::array<_Tp, _Nm>&, unsigned int)'
```
I think BTAS should not include serialization for std::array.

**Comment by evaleev** [comment]
Re: boost serialization for std::array : which version of boost do you use? boost itself defines it since 1.56.0 . If boost version < 1.56, someone has to define it. Does BAGEL has a definition for this template turned on by some preprocessor flag?

**Comment by shiozaki** [comment]
The on my laptop was 1.55. I can set it in bagel - Is it literally BOOST_SERIALIZATION_STD_ARRAY?

**Comment by evaleev** [comment]
you don't need to define BOOST_SERIALIZATION_STD_ARRAY any longer, even if
boost does not define serialization for std::array, btas will.

On Wed, Jan 14, 2015 at 1:28 PM, Toru Shiozaki <notifications@github.com>
wrote:

> The on my laptop was 1.55. I can set it in bagel - Is it literally
> BOOST_SERIALIZATION_STD_ARRAY?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BTAS/BTAS/pull/74#issuecomment-69965336>.
>



-- 
web: valeyev.net

**Comment by shiozaki** [comment]
No, users may have std::array serialization and may not want to delegate it to BTAS (this is a philosophical question). Imagine I have two sets of tensor libraries and switch back and forth. I want to keep the one in BAGEL.

**Comment by evaleev** [comment]
As of 1.56 this is no longer an option as boost provides it and user's
serialization will conflict.


On Wed, Jan 14, 2015 at 1:35 PM, Toru Shiozaki <notifications@github.com>
wrote:

> No, users may have std::array serialization and may not want to delegate
> it to BTAS (this is a philosophical question). Imagine I have two sets of
> tensor libraries and switch back and forth. I want to keep the one in BAGEL.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/BTAS/BTAS/pull/74#issuecomment-69966434>.
>



-- 
web: valeyev.net

**Comment by shiozaki** [comment]
I understood, but that can be solved in BAGEL. My problem above cannot be solved in BAGEL (i.e., user side).

**Comment by evaleev** [comment]
How about the BTAS-provided boost::serialization::serialize(std::array...) is provided by default for <1.56, but can be disabled (rather than need to be enabled explicitly). This way most users can do nothing and get array serialization for free if their boost is not up to date. Experts can override this behavior (the question to experts then: why ability to override serializtion for array is important but not for vector?)

**Comment by shiozaki** [comment]
Yes, I think it is fine with me. Probably you could just insert \#ifndef \#endif ?

**Comment by evaleev** [comment]
OK done.

**Comment by shiozaki** [comment]
@evaleev this could be merged as far as bagel is concerned.

**Comment by evaleev** [comment]
Toru @shiozaki, thanks!

**Pull request merged**
